config/routes.rb
Coffeebreak::Application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout' 

  resources :sessions
  resources :orders
  resources :messages
  resources :users
  root to: 'users#home'
end

app/models/message.rb
class Message < ActiveRecord::Base

  before_create :send_message

  belongs_to :order
  belongs_to :user

private

  def send_message
    response = RestClient::Request.new(
      :method => :post,
      :url => 'https://api.twilio.com/2010-04-01/Accounts/AC5d1d1f64e78a275baa28a4bbe4165f43/Messages.json',
      :user => ENV['TWILIO_ACCOUNT_SID'],
      :password => ENV['TWILIO_AUTH_TOKEN'],
      :payload => { :Body => body,
                    :To => to,
                    :From => from }
    ).execute
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  validates :name, :presence => true
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :orders
  validates_uniqueness_of :email
  validates :name, presence: true
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end  

  helper_method :current_user

  def authorize 
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end  
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  
  skip_before_action :verify_authenticity_token

  def index
    @messages = Message.all
  end  

  def new
    @user = current_user
    @message = Message.new
  end
  
  def create 
    @message = Message.new(message_params)
    if @message.save
      render "success"
    else
      render 'new'
    end  
  end  

  def show
    @message = Message.find(params[:id])
  end  

private

  def message_params
    params.require(:message).permit(:to, :from, :body)
  end  
end  

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    def home

    end  

    def index
      @orders = Order.all
    end  

    def new
      @order = Order.new
    end
    
    def create 
      @order = Order.new(order_params)
      if @order.save
        redirect_to new_message_path
      else
        render 'new'
      end  
    end  

    def show
      @order= Order.find(params[:id])
    end

    def edit
      @order = Order.find(params[:id])
    end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      redirect_to order_path(@order), notice: "Order updated successfully"
    else
      render 'edit', notice: "Invalid entry. Please try again."
    end
  end

    def destroy
      @order = Order.find(params[:id])
      @order.destroy
      render "success"
    end  

  def order_params
    params.require(:order).permit(:drink_category, :name, :size, :milk, :flavor, :user_name, :id)
  end   
end  

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:notice] = "Logged in!"
      redirect_to root_path
    else
      flash.now[:alert] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out!"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create  
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new" 
    end
  end     

private

def user_params
  params.require(:user).permit(:email, :name, :title, :avatar, :password, :password_confirmation)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag  "application", "vendor/modernizr", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>

  </head>

  <body>

  <nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><a href="#">CoffeeBreak</a></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
          <% if current_user %>
              <li class="active"><%= link_to "Log Out", logout_path %></li>
           <% else %>   
             <li class="active"><%= link_to "Login", login_path %></li>
             <li class="active"><%= link_to "Sign Up", signup_path %></li>
          <% end %>  
    </ul>

    <!-- Left Nav Section -->
    <ul class="left">
      
    </ul>
  </section>
</nav>

  <div class="row">
    <br>
    <br>
    <%= yield %>
  </div>


       

      <%= flash[:alert] %>
      <%= flash[:notice] %>
    </div>
  </body>
</html>

app/views/messages/new.html.erb
<h1>New Message</h1>

<% if @message.errors.any? %>
  <p>Something went wrong:</p>
  <ul>
    <% message.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>      


<%= form_for @message do |f| %>
  <%= f.label :to %>
  <%= f.text_field :to %>
  <%= f.label :from %>
  <%= f.text_field :from %>
  <%= f.hidden_field :body, :value => "Your officemate wants a coffee! Log into CoffeeBreak to make someone's dream come true!"  %>
  <%= f.submit "Send Order", class: "button" %>
<% end %>  

app/views/messages/success.html.erb
SUCCESS!!!

app/views/orders/index.html.erb
<h1>See all current orders</h1>

<p>Click fill order to choose the person you would like to treat!</p>

<div class="row">
    <div class="small-2 large-4 columns">
      <% @orders.each do |order| %>
        <%= image_tag current_user.avatar(:medium) %>
        <%= link_to order.name, order_path(order) %> for <%= order.user_name %>
      <% end %>
    </div>
</div>    

app/views/orders/new.html.erb
<h1>New Order</h1>
   
  <%= form_for @order do |f| %>
  <%= f.label :drink_category %>
  <%= f.text_field :drink_category %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :milk %>
  <%= f.text_field :milk %>
  <%= f.label :flavor %>
  <%= f.text_field :flavor %>
  <%= f.label :size %>
  <%= f.text_field :size %>
  <%= f.hidden_field :user_name, :value => current_user.name  %>
  <%= f.submit "Save order", class: "button" %>
<% end %>  

app/views/orders/show.html.erb
<div class="row">
  <%= @order.user_name %> wants the following: 
</div>
<div class="row">
  <%= @order.drink_category %>
</div>
<div class="row">
  <%= @order.name %>
</div>
<div class="row">
  <%= @order.milk %>
</div>
<div class="row">
  <%= @order.flavor %>
</div>
<div class="row">
  <%= @order.size %>
</div>
<div class="row">
  <%= link_to "Buy it!", order_path(@order), 
                              :data => {:confirm => "You sure?",
                                        :method => "delete"}, class: "button" %>
</div>                                        

app/views/orders/success.html.erb
<h1>You are a model citizen. You get a raise!</h1>

app/views/users/home.html.erb
<div class="row">
  <div class="large-6 columns">
    <%= image_tag("coffeecup.png", height: '50%', width: '50%', class: "front_page_image") %>
  </div>  
  <div class="large-6 columns">
    <%= image_tag("coffeebr.png", height: '70%', width: '70%', class: "front_page_image") %>
    <h4>Text your order and send your friend on a coffee run.</h4>
    <%= link_to "Place an order", new_order_path, class: "button" %>
    <%= link_to "Fill an order", orders_path, class: "button" %>
  </div>
</div>
<br>
<br>
<div class="row">
  
</div>

app/views/users/index.html.erb
All the users

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>  
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
   <%= f.file_field :avatar %>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>

app/views/users/show.html.erb
<div class="row">
  <%= image_tag current_user.avatar %>
</div>
<div class="row">
  <%= current_user.name %>
</div>  